VOLATILITY_TARGET: 0.15

START_DATE: "2007-10-19"

# Leave END_DATE empty to just use today.
# END_DATE: "2020-06-22"

BENCHMARK_TICKER: "VTI"

ENVIRONMENTS:
  RISING_GROWTH: ["VTI", "DBC"]
  FALLING_GROWTH: ["GLD", "TLT"]
  RISING_INFLATION: ["GLD", "DBC"]
  FALLING_INFLATION: ["VTI", "TLT"]

OUTPUT_FILE: "backtest.csv"